### PR TITLE
Employer friendly commit name.

### PR DESCRIPTION
**Pull request by samfumanti**

### CODE REVIEW

**Comment by frankMazzarella** [comment]
what even is this?

**Comment by samfumanti** [comment]
It is a penis inseminating a vagina. I understand if you don't know what
that looks like.

**Comment by frankMazzarella** [comment]
I was more concerned with the actual code changes, it looks like you moved everything into a src directory.... inside of the src directory. Does this even run? You realize there is no way to view changes since every file is now a new file right? 

Like I said, ask me for help if you need it (you may). I cant accept this and allow the develop branch to degrade, and yes very nice penis.

**Comment by samfumanti** [comment]
Ohhh didn't realize it did that. It looked normal on my end. Fine I'll fix
it

**Comment by frankMazzarella** [comment]
Closing in favor of PR#6

**Pull request closed without merging**
